version: "3.9"

services:
  grype:
    image: anchore/grype:0.76.0
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "grype version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

