version: "3.9"

services:
  zipkin:
    image: openzipkin/zipkin:2.24.3
    ports:
      - "9411:9411"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9411/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

