version: "3.9"

services:
  trivy:
    image: aquasec/trivy:0.52.2
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "trivy --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

