version: "3.9"

services:
  sqlite-web:
    image: coleifer/sqlite-web:${SQLITE_TAG:-latest}
    environment:
      - SQLITE_DATABASE=/data/db.sqlite
    ports:
      - "${SQLITE_WEB_PORT:-8081}:8080"
    volumes:
      - sqlite-data-${SQLITE_TAG:-latest}:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlite-data-latest:

