version: "3.9"

services:
  mailpit:
    image: axllent/mailpit:v1.20.2
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8025/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

